### ISSUE TITLE
Some suggestions of code

### ISSUE THREAD

**Issue by ho-229** [MCUmbrella/ProjectNuma#1]
1. Here should be written as a virtual functions instead of function pointers:
https://github.com/MCUmbrella/ProjectNuma/blob/19410e132a90f4abb481c7bd0b0197e476113461/src/Main.cpp#L50-L56

eg.

```cpp
virtual void beforeTick() = default;
```
than Player inherits Entity and overrides beforeTick like:

```cpp
void beforeTick() override { // do something }
```

2. Implementation should be moved to the other .h/.cpp files.

**Comment by MCUmbrella** [comment]
suggestion1 is nice but
![image](https://user-images.githubusercontent.com/40854260/202730443-14dcb3a8-3fde-4871-8967-a7bfd30dfb68.png)

**Comment by ho-229** [comment]
this is wrong usage
virtual functions in cpp are like interface in java

**Comment by MCUmbrella** [comment]
i know this is wrong usage and im now asking how to change these lines to make them fit your changes

**Comment by ho-229** [comment]
in this case, you should override afterTick in Bullet
eg.
```cpp
class Bullet : public Entity {
public:
    void afterTick() override { --this->hp; }
}
```

**Comment by MCUmbrella** [comment]
我是想只让某个特定的Bullet对象覆盖父类的afterTick函数，有没有办法实现？
还有上边的这句`virtual void beforeTick() = default;`
编译器会报错：Only special member functions may be defaulted
所以我现在只能写成`virtual void beforeTick(){}`

**Comment by ho-229** [comment]
噢，第一个应该是 = 0;
如果实现不一样的话就没办法这样用
不过可以把函数指针改成std::function对象

**Comment by MCUmbrella** [comment]
issue里描述的问题基本上全解决了
